
tf_docker: &tf-docker
  image: "${TERRAFORM_IMAGE}"
  entrypoint: /bin/ash
steps:
  - label: ":terraform: Init"
    plugins:
    - docker#v5.6.0:
        <<: *tf-docker
        image: "hashicorp/terraform:1.4.2"
        mount-checkout: true
        entrypoint: /bin/ash
        command:
          - -e
          - -c
          - |
            cd terraform && terraform init
            terraform plan
