tf_docker: &tf-docker
  image: "${TERRAFORM_IMAGE}"
  entrypoint: /bin/bash

steps:
  - label: ":terraform: Init && Plan"
    plugins:
      - docker#v5.6.0:
          <<: *tf-docker
          image: "${TERRAFORM_IMAGE}"
          mount-checkout: true
          propagate-environment: true
          entrypoint: /bin/ash
          command:
            - -e
            - -c
            - |
              cd terraform && terraform init
              terraform plan


  - label: ":terraform: Apply"
    artifact_paths: "terraform/rules/*"
    plugins:
      - docker#v5.6.0:
          <<: *tf-docker
          image: "${TERRAFORM_IMAGE}"
          mount-checkout: true
          propagate-environment: true
          entrypoint: /bin/ash
          command:
            - -e
            - -c
            - |
              cd terraform && terraform init
              terraform apply --auto-approve

  - label: ":terraform: Destroy"
    plugins:
    - docker#v5.6.0:
        <<: *tf-docker
        image: "${TERRAFORM_IMAGE}"
        mount-checkout: true
        propagate-environment: true
        entrypoint: /bin/ash
        command:
          - -e
          - -c
          - |
            cd terraform && terraform init
            terraform apply -destroy --auto-approve